### ISSUE TITLE
405 method not allowed - when posting json

### ISSUE THREAD

**Issue by alfhen** [skipperbent/http-service#14]
Laravel rejects the httpRequest made from `execute() in HttpRequest.php`when making a JSON POST request.
It happens because Laravel expects the ?_method=<method> to be present in the url and not part of the JSON body.
To fix it i had to add the following code to line `136 in HttpRequest.php`
``` php
		if (strtolower($this->method) !== 'get' && $this->postJson) {
			$method = strpos($this->url, '?') ?
				http_build_query(['_method' => $this->method]) :
				'?'.http_build_query(['_method' => $this->method]);
			$this->url = $this->url .$method;
		}
```

**Comment by skipperbent** [comment]
Thanks!

Fixed in version 1.0.12

https://github.com/skipperbent/http-service/releases/tag/1.0.12
